# Generated by Django 6.0.6 on 2026-06-28 19:58

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0000_create_vector_extension"),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_id', models.IntegerField(db_index=True)),
                ('chunk_index', models.IntegerField()),
                ('text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
            ],
            options={
                'db_table': 'resume_chunks',
                'indexes': [models.Index(fields=['resume_id'], name='resume_chun_resume__7ed43e_idx')],
            },
        ),
    ]
