# Generated by Django 6.0.6 on 2026-06-28 19:58

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0000_create_vector_extension"),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=500)),
                ('categories', models.JSONField(default=list)),
                ('status', models.CharField(default='Not Available', max_length=50)),
                ('thumbnail_key', models.CharField(blank=True, max_length=500)),
                ('source_file_key', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(db_index=True)),
                ('subtopic_order', models.PositiveIntegerField()),
                ('chunk_index', models.IntegerField()),
                ('text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
            ],
            options={
                'db_table': 'course_chunks',
                'indexes': [models.Index(fields=['course_id', 'subtopic_order'], name='course_chun_course__10b6cf_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskRecord',
            fields=[
                ('task_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('task_type', models.CharField(max_length=50)),
                ('status', models.CharField(default='running', max_length=20)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
            options={
                'db_table': 'task_records',
            },
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('difficulty', models.CharField(default='Intermediate', max_length=20)),
                ('order', models.PositiveIntegerField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('content_key', models.CharField(blank=True, max_length=500)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='courses.course')),
            ],
            options={
                'db_table': 'subtopics',
                'ordering': ['order'],
                'unique_together': {('course', 'order')},
            },
        ),
    ]
