# Generated by Django 6.0.6 on 2026-06-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('resume_id', models.IntegerField(db_index=True)),
                ('resume_name', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
